FROM rust:1-trixie

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        pkg-config \
        libssl-dev \
    && rm -rf /var/lib/apt/lists/*

COPY Cargo.toml Cargo.lock ./

COPY src ./src
COPY frontend ./frontend
COPY models ./models
COPY migrations ./migrations

RUN cargo build --release

COPY database ./database

EXPOSE 3000

CMD ["./target/release/Image_Crop1"]